# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('key_positions', models.CharField(max_length=200)),
                ('create_datetime', models.DateTimeField()),
                ('last_update_datetime', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField()),
                ('cost_time', models.IntegerField()),
                ('group', models.IntegerField()),
            ],
        ),
    ]
