# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_labeled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='cost_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AlterField(
            model_name='content',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='key_positions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='last_update_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='content',
            name='last_update_user',
            field=models.IntegerField(null=True),
        ),
    ]
