# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0002_auto_20171205_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField(null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='group',
            new_name='group_id',
        ),
        migrations.AlterField(
            model_name='content',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期'),
        ),
    ]
