# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0003_auto_20171205_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='collected_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField(null=True)),
            ],
        ),
    ]
