# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0004_collected_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='key_positions',
        ),
        migrations.AddField(
            model_name='content',
            name='key1_positions',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='key2_positions',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
