# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0006_auto_20171211_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
