# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0007_content_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('settings', models.CharField(max_length=500)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
