# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0008_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='setting_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
