# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0009_settings_setting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='settings_id',
            field=models.IntegerField(null=True),
        ),
    ]
