# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0011_content_classfy_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='classfy_list',
            new_name='class_list',
        ),
    ]
