# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0012_auto_20171225_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_single',
            field=models.BooleanField(default=False),
        ),
    ]
