# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0013_settings_is_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_group',
            name='settings_id',
            field=models.IntegerField(null=True),
        ),
    ]
