# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0015_content_is_dirty_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField(null=True)),
                ('feedback_question', models.TextField(max_length=1500)),
                ('feedback_answer', models.TextField(max_length=1500)),
            ],
        ),
    ]
