# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0017_auto_20180312_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_content',
            name='last_update_user',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
